{
    "id": "CVE-2019-19844",
    "cisaKEV": false,
    "reported_exploited": false,
    "exploit_maturity": "poc",
    "counts": {
        "public_exploit_count": 4
    },
    "timeline": {
        "nvd_published": "2019-12-18"
    },
    "exploits": [
        {
            "url": "https://gitlab.com/exploit-database/exploitdb/-/blob/main/exploits/python/webapps/47879.md",
            "name": "Django < 3.0 < 2.2 < 1.11 - Account Hijack",
            "source": "exploitdb",
            "date_added": "2019-12-24",
            "exploit_maturity": "poc"
        },
        {
            "url": "https://github.com/ryu22e/django_cve_2019_19844_poc",
            "name": "PoC for CVE-2019-19844(https://www.djangoproject.com/weblog/2019/dec/18/security-releases/)",
            "source": "github",
            "date_added": "2019-12-21",
            "exploit_maturity": "poc"
        },
        {
            "url": "https://github.com/andripwn/django_cve201919844",
            "name": "PoC for CVE-2019-19844 ( https://www.djangoproject.com/weblog/2019/dec/18/security-releases/ )",
            "source": "github",
            "date_added": "2019-12-25",
            "exploit_maturity": "poc"
        },
        {
            "url": "https://packetstormsecurity.com/files/download/155872/django_cve_2019_19844_poc-master.tgz",
            "name": "Django Account Hijack",
            "source": "packetstorm",
            "date_added": "2020-01-08",
            "exploit_maturity": "poc"
        }
    ]
}